# Generated by Django 5.2.11 on 2026-03-03 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='workmode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='experience',
            field=models.TextField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='location',
            field=models.TextField(max_length=15),
        ),
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='jobtypes',
            name='name',
            field=models.TextField(max_length=15),
        ),
        migrations.AlterField(
            model_name='skills',
            name='name',
            field=models.TextField(max_length=15),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='location',
            field=models.TextField(max_length=15),
        ),
        migrations.AddField(
            model_name='job',
            name='workmd',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.workmode'),
        ),
    ]
