# Generated by Django 5.2.11 on 2026-03-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_workmode_job_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='about',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
