# Generated by Django 5.2.11 on 2026-03-09 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_companyprofile_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_skills',
            field=models.ManyToManyField(blank=True, to='home.skills'),
        ),
        migrations.CreateModel(
            name='application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.userprofile')),
                ('applied_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.job')),
            ],
            options={
                'unique_together': {('applicant', 'applied_job')},
            },
        ),
    ]
