# Generated by Django 5.2.11 on 2026-03-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_userprofile_user_skills_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='tagline',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
    ]
