# Generated by Django 5.2.11 on 2026-03-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_companyprofile_tagline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='about',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
