# Generated by Django 5.2.11 on 2026-03-23 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_userprofile_about_userprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='tagline',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
